export const actionTypes = {
    GET_INVITATIONS: 'invitations/GET_INVITATIONS',
    ACCEPT_INVITATION: 'invitations/ACCEPT_INVITATION',
    DECLINE_INVITATION: 'invitations/DECLINE_INVITATION',
    GET_INVITATIONS_PENDING: 'invitations/GET_INVITATIONS_PENDING',
    GET_INVITATIONS_ACCEPTED: 'invitations/GET_INVITATIONS_ACCEPTED',
    GET_INVITATIONS_DECLINED: 'invitations/GET_INVITATIONS_DECLINED',
    // TODO: ADD_INVITATION, EDIT_INVITATION, ACCEPT_INVITATION, DECLINE_INVITATION
}