export const actionTypes = {
    LOGIN: 'users/login',
    REGISTER: 'users/register',
    RESET_PASSWORD: 'users/resetPassword',
    GET_MEETUPS_CREATED: 'users/getMeetupsCreated',
    GET_MEETUPS_PENDING: 'users/getMeetupsPending',
    GET_MEETUPS_ACCEPTED: 'users/getMeetupsAccepted',
    GET_MEETUPS_DECLINED: 'users/getMeetupsDeclined',
    ACCEPT_MEETUP: 'users/acceptMeetup',
    DECLINE_MEETUP: 'users/declineMeetup',
    GET_FRIENDS: 'users/friends',
    GET_FRIEND_REQUESTS: 'users/getFriendRequests',
    GET_FRIEND_REQUESTS_SENT: 'users/getFriendRequestsSent',
    SEND_FRIEND_REQUEST: 'users/sendFriendRequest',
    DELETE_FRIEND: 'users/deleteFriend',
    ACCEPT_FRIEND_REQUEST: 'users/acceptFriendRequest',
    DECLINE_FRIEND_REQUEST: 'users/declineFriendRequest',
}