export const actionTypes = {
    LOGIN: 'users/login',
    REGISTER: 'users/register',
    RESET_PASSWORD: 'users/reset-password',
    GET_MEETUPS_CREATED: 'users/meetups/created',
    GET_MEETUPS_PENDING: 'users/meetups/pending',
    GET_MEETUPS_ACCEPTED: 'users/meetups/accepted',
    GET_MEETUPS_DECLINED: 'users/meetups/declined',
    ACCEPT_MEETUP: 'users/meetups/pending/accept',
    DECLINE_MEETUP: 'users/meetups/pending/decline',
    GET_FRIENDS: 'users/friends',
    GET_FRIEND_REQUESTS: 'users/friends/requests',
    GET_FRIEND_REQUESTS_SENT: 'users/requests/sent',
    SEND_FRIEND_REQUEST: 'users/friends/requests/send',
    DELETE_FRIEND: 'users/friends/delete',
    ACCEPT_FRIEND_REQUEST: 'users/friends/requests/accept',
    DECLINE_FRIEND_REQUEST: 'users/friends/requests/decline',
}